name: Deploy docker image and update production

on:
    push:
        branches:
            - "main"

env:
    ENV_KEYS: >-
        MONGO_URI
        DISCORD_CLIENT_ID
        DISCORD_CLIENT_SECRET
        DISCORD_BOT_TOKEN
        DISCORD_GUILD_MEMBER_ROLE_ID
        DISCORD_GUILD_ID
        JWT_SECRET
        SPACE_ELECTRICITY_TRACKER_SLUG

    # Application environment variables
    GIT_COMMIT_SHA: ${{ github.sha }}
    MONGO_URI: ${{ secrets.MONGO_URI }}
    DISCORD_CLIENT_ID: ${{ vars.DISCORD_CLIENT_ID }}
    DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
    DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
    DISCORD_GUILD_MEMBER_ROLE_ID: ${{ vars.DISCORD_GUILD_MEMBER_ROLE_ID }}
    DISCORD_GUILD_ID: ${{ vars.DISCORD_GUILD_ID }}
    JWT_SECRET: ${{ secrets.JWT_SECRET }}
    SPACE_ELECTRICITY_TRACKER_SLUG: ${{ vars.SPACE_ELECTRICITY_TRACKER_SLUG }}
    
    # Docker image configuration
    IMAGE_NAME: nu31hackerspace/space
    DOCKER_STACK_NAME: nu31space
    REGISTRY: ghcr.io
    
    # Deployment configuration
    DEPLOY_USER: deploy
    HOST: ${{ vars.HOST }}
    DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: "true"

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
                  build-args: |
                      GIT_COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}

    deploy:
        runs-on: ubuntu-latest
        needs:
            - build-and-push-image
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Create .env file for Docker Stack
              run: |
                  echo "IMAGE_NAME='$IMAGE_NAME'" >> .env
                  echo "GIT_COMMIT_SHA='$GIT_COMMIT_SHA'" >> .env
                  for key in $ENV_KEYS; do
                      echo "$key='${!key}'" >> .env
                  done

            - name: Docker Stack Deploy
              uses: cssnr/stack-deploy-action@v1
              with:
                  name: ${{ env.DOCKER_STACK_NAME }}
                  file: docker-stack.yml
                  host: ${{ env.HOST }}
                  port: 22
                  user: ${{ env.DEPLOY_USER }}
                  ssh_key: ${{ env.DEPLOY_SSH_PRIVATE_KEY }}
                  env_file: .env
                  detach: false
                  prune: true
                  resolve_image: 'always'
                  summary: true
